version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  eb: circleci/aws-elastic-beanstalk@1.0.0

jobs:
  build:
    docker:
      - image: cimg/node:18.12.1
    steps:     
      - checkout
      # Use root level package.json to install dependencies in the frontend app
      - run:
          name: Install Front-End Dependencies
          command: cd client && npm install
      # TODO: Install dependencies in the the backend API          
      - run:
          name: Install API Dependencies
          command: cd server && npm install
      # TODO: Test the frontend
      - run:
          name: Front-End test
          command: cd client && npm run test
      # TODO: Test the API
      - run:
          name: API test
          command: cd server && npm run test
      # TODO: Build the frontend app
      - run:
          name: Front-End Build
          command: cd client && npm run build
      # TODO: Build the backend API      
      - run:
          name: API Build
          command: cd server && npm run build

  deploy:
    docker:
      - image: cimg/node:18.12.1
      # more setup needed for aws, elastic beanstalk
    steps:
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: cd client && npm install
      - run:
          name: Install API Dependencies
          command: cd server && npm install
      - run:
          name: Deploy App
          # TODO: Install, build, deploy in both apps
          command: cd client && npm run deploy
            
workflows:
  circle-ci-pipeline:
    jobs:
      - build
      - deploy:
          requires:
            - build